### PR TITLE
support test with table cache

### PR DESCRIPTION
**Pull request by zyguan**
Signed-off-by: zyguan <zhongyangguan@gmail.com>

### CODE REVIEW

**Comment by cfzjywxk** [comment]
Is it enabled by default now?

**Comment by zyguan** [comment]
> Is it enabled by default now?

No, `--table-cache` is required to enable it.

I'm planning to add extra test plans for table cache, which can be scheduled less frequently.

**Comment by zyguan** [comment]
orz http://rms.pingcap.net:31714/artifacts/testground/plan-exec-1080251/plan-exec-1080251-2643014133/archive

**Comment by zyguan** [comment]
@cfzjywxk The bug is under investigation. Maybe we can merge this PR first.

**Review by cfzjywxk — APPROVED** [review]

**Pull request merged**
