### PR TITLE
add support for setting isolation level

### PR DESCRIPTION
**Pull request by zyguan**
Signed-off-by: zyguan <zhongyangguan@gmail.com>

### CODE REVIEW

**Review by youjiali1995 — APPROVED** [review]
LGTM. However, I can't fully understand it.

**Comment by cfzjywxk** [comment]
> LGTM. However, I can't fully understand it.

@youjiali1995 
I think it's used to test some suitable cases using `READ-COMMITTED` isolation level? 

@zyguan 
Should we just make changes to these suitable cases?

**Comment by youjiali1995** [comment]
I just can't know whether it can work because I'm not familiar with closure. 😂

**Comment by cfzjywxk** [comment]
> I just can't know whether it can work because I'm not familiar with closure. 😂

Me too  😂.  I think most Jepsen cases are not very suitable for `READ-COMMITTED` tests.

**Comment by zyguan** [comment]
> Should we just make changes to these suitable cases?

@cfzjywxk It can be controlled by command argument `--isolation`, if RC is not suitable for some of workloads, we just do not run them.

**Comment by cfzjywxk** [comment]
> > Should we just make changes to these suitable cases?
> 
> @cfzjywxk It can be controlled by command argument `--isolation`, if RC is not suitable for some of workloads, we just do not run them.

Could we report an error if RC is not suitable for this, or record some error logs to notify users.

**Comment by zyguan** [comment]
> Could we report an error if RC is not suitable for this, or record some error logs to notify users.

@cfzjywxk I think so, besides the default isolation level is still RR, I believe this PR won't break current tests. 

I'm also working on a document about jepsen test models, I think we can optimize (to choose combinations of nemsis, txn-mode, isolation, etc.) jepsen tests according to that.

**Comment by cfzjywxk** [comment]
LGTM

**Pull request merged**
