### PR TITLE
log txn info if available

### PR DESCRIPTION
**Pull request by zyguan**
Signed-off-by: zyguan <zhongyangguan@gmail.com>

This PR depends on https://github.com/pingcap/tidb/pull/19949 .

<details>
<summary>Here is an example</summary>

```
2020-09-11 15:37:05,049{GMT}	INFO	[jepsen worker 6-172.28.1.2] jepsen.util: 6	:ok	:txn	[[:r 3 [1 3]] [:append 1 6]]	{"start_ts" 419388096451182615, "commit_ts" 419388096516718610}
2020-09-11 15:37:05,050{GMT}	INFO	[jepsen worker 6-172.28.1.2] jepsen.util: 6	:invoke	:txn	[[:r 2 nil]]
2020-09-11 15:37:05,054{GMT}	INFO	[jepsen worker 6-172.28.1.2] jepsen.util: 6	:ok	:txn	[[:r 2 [2 1 3]]]	{"start_ts" 419388096451182615, "commit_ts" 419388096516718610}
2020-09-11 15:37:05,054{GMT}	INFO	[jepsen worker 6-172.28.1.2] jepsen.util: 6	:invoke	:txn	[[:r 0 nil] [:append 0 9] [:append 4 5]]
2020-09-11 15:37:05,067{GMT}	INFO	[jepsen worker 2-172.28.1.3] jepsen.util: 2	:ok	:txn	[[:append 1 9]]	{"start_ts" 419388096516718609, "commit_ts" 419388096516718625}
2020-09-11 15:37:05,068{GMT}	INFO	[jepsen worker 2-172.28.1.3] jepsen.util: 2	:invoke	:txn	[[:append 1 10] [:append 3 6] [:r 0 nil]]
2020-09-11 15:37:05,107{GMT}	INFO	[jepsen worker 7-172.28.1.3] jepsen.util: 7	:ok	:txn	[[:r 3 [1 3]] [:r 0 [1 4 3 5 6]]]	{"start_ts" 419388096451182626, "commit_ts" 419388096530087957}
2020-09-11 15:37:05,107{GMT}	INFO	[jepsen worker 7-172.28.1.3] jepsen.util: 7	:invoke	:txn	[[:append 2 5] [:r 4 nil]]
2020-09-11 15:37:05,136{GMT}	INFO	[jepsen worker 8-172.28.1.4] jepsen.util: 8	:ok	:txn	[[:append 1 8]]	{"start_ts" 419388096490504212, "commit_ts" 419388096543195147}
2020-09-11 15:37:05,136{GMT}	INFO	[jepsen worker 8-172.28.1.4] jepsen.util: 8	:invoke	:txn	[[:r 0 nil]]
2020-09-11 15:37:05,142{GMT}	INFO	[jepsen worker 8-172.28.1.4] jepsen.util: 8	:ok	:txn	[[:r 0 [1 4 3 5 6]]]	{"start_ts" 419388096490504212, "commit_ts" 419388096543195147}
2020-09-11 15:37:05,142{GMT}	INFO	[jepsen worker 8-172.28.1.4] jepsen.util: 8	:invoke	:txn	[[:r 4 nil] [:r 3 nil]]
2020-09-11 15:37:05,153{GMT}	INFO	[jepsen worker 9-172.28.1.5] jepsen.util: 9	:ok	:txn	[[:append 3 5] [:append 0 7] [:append 1 7]]	{"start_ts" 419388096477397004, "commit_ts" 419388096543195163}
2020-09-11 15:37:05,153{GMT}	INFO	[jepsen worker 9-172.28.1.5] jepsen.util: 9	:invoke	:txn	[[:append 3 7]]
2020-09-11 15:37:05,281{GMT}	INFO	[jepsen worker 4-172.28.1.5] jepsen.util: 4	:ok	:txn	[[:r 4 [2 4]] [:append 4 1] [:append 3 4] [:r 1 [3 5 1 2 6 9 8 7]]]	{"start_ts" 419388096530087947, "commit_ts" 419388096582254593}
2020-09-11 15:37:05,281{GMT}	INFO	[jepsen worker 4-172.28.1.5] jepsen.util: 4	:invoke	:txn	[[:append 3 8] [:append 1 11] [:r 2 nil]]
2020-09-11 15:37:05,303{GMT}	INFO	[jepsen worker 6-172.28.1.2] jepsen.util: 6	:ok	:txn	[[:r 0 [1 4 3 5 6 7]] [:append 0 9] [:append 4 5]]	{"start_ts" 419388096516718624, "commit_ts" 419388096582254608}
2020-09-11 15:37:05,304{GMT}	INFO	[jepsen worker 6-172.28.1.2] jepsen.util: 6	:invoke	:txn	[[:append 1 12] [:append 1 13]]
2020-09-11 15:37:05,305{GMT}	INFO	[jepsen worker 9-172.28.1.5] jepsen.util: 9	:ok	:txn	[[:append 3 7]]	{"start_ts" 419388096543195172, "commit_ts" 419388096582254609}
2020-09-11 15:37:05,306{GMT}	INFO	[jepsen worker 9-172.28.1.5] jepsen.util: 9	:invoke	:txn	[[:r 0 nil] [:r 1 nil] [:r 0 nil]]
2020-09-11 15:37:05,321{GMT}	INFO	[jepsen worker 7-172.28.1.3] jepsen.util: 7	:ok	:txn	[[:append 2 5] [:r 4 [2 4 1 5]]]	{"start_ts" 419388096530087966, "commit_ts" 419388096582254627}
2020-09-11 15:37:05,322{GMT}	INFO	[jepsen worker 7-172.28.1.3] jepsen.util: 7	:invoke	:txn	[[:r 2 nil] [:r 2 nil]]
2020-09-11 15:37:05,342{GMT}	INFO	[jepsen worker 7-172.28.1.3] jepsen.util: 7	:ok	:txn	[[:r 2 [2 1 3 5]] [:r 2 [2 1 3 5]]]	{"start_ts" 419388096595361800, "commit_ts" 419388096595361806}
2020-09-11 15:37:05,343{GMT}	INFO	[jepsen worker 7-172.28.1.3] jepsen.util: 7	:invoke	:txn	[[:append 4 6] [:append 0 10]]
2020-09-11 15:37:05,381{GMT}	INFO	[jepsen worker 3-172.28.1.4] jepsen.util: 3	:ok	:txn	[[:r 3 [1 3 5 4 7]] [:r 1 [3 5 1 2 6 9 8 7]] [:append 2 4]]	{"start_ts" 419388096569147400, "commit_ts" 419388096595361838}
2020-09-11 15:37:05,382{GMT}	INFO	[jepsen worker 3-172.28.1.4] jepsen.util: 3	:invoke	:txn	[[:append 1 14] [:r 4 nil] [:r 0 nil]]
2020-09-11 15:37:05,405{GMT}	INFO	[jepsen worker 8-172.28.1.4] jepsen.util: 8	:ok	:txn	[[:r 4 [2 4 1 5]] [:r 3 [1 3 5 4 7]]]	{"start_ts" 419388096543195162, "commit_ts" 419388096608731143}
2020-09-11 15:37:05,405{GMT}	INFO	[jepsen worker 8-172.28.1.4] jepsen.util: 8	:invoke	:txn	[[:r 1 nil] [:append 4 7] [:r 2 nil] [:append 1 15]]
2020-09-11 15:37:05,465{GMT}	INFO	[jepsen worker 6-172.28.1.2] jepsen.util: 6	:ok	:txn	[[:append 1 12] [:append 1 13]]	{"start_ts" 419388096582254622, "commit_ts" 419388096621838367}
2020-09-11 15:37:05,466{GMT}	INFO	[jepsen worker 6-172.28.1.2] jepsen.util: 6	:invoke	:txn	[[:r 2 nil] [:r 1 nil] [:append 0 11]]
2020-09-11 15:37:05,510{GMT}	INFO	[jepsen worker 4-172.28.1.5] jepsen.util: 4	:ok	:txn	[[:append 3 8] [:append 1 11] [:r 2 [2 1 3 5 4]]]	{"start_ts" 419388096582254604, "commit_ts" 419388096635731984}
2020-09-11 15:37:05,510{GMT}	INFO	[jepsen worker 4-172.28.1.5] jepsen.util: 4	:invoke	:txn	[[:append 0 12]]
2020-09-11 15:37:05,530{GMT}	INFO	[jepsen worker 9-172.28.1.5] jepsen.util: 9	:ok	:txn	[[:r 0 [1 4 3 5 6 7 9]] [:r 1 [3 5 1 2 6 9 8 7 12 13 11]] [:r 0 [1 4 3 5 6 7 9]]]	{"start_ts" 419388096582254626, "commit_ts" 419388096647790594}
```

</details>

### CODE REVIEW

**Comment by zyguan** [comment]
There is one limitation: for a single select statement, we can not get ts info currently.

Two workloads are affected: set & sequential.

**Comment by cfzjywxk** [comment]
> There is one limitation: for a single select statement, we can not get ts info currently.
> 
> Two workloads are affected: set & sequential.

Do you mean the `autocommit` transaction with a single select read statement without `for update`? For this maybe we need hook the statement execution finish stage for autocommit transaction to get the `startTS` or `snapshotTS`.

**Comment by zyguan** [comment]
```sql
set autocommit=0;
select * from t;
select @@tidb_current_ts;
set autocommit=1;
```
Yes, in the above case, we can get the start ts from `tidb_current_ts`. Bug if `autocommit=1`, we can not get the ts used by a select statement (even when using `for update`).

**Comment by zyguan** [comment]
There is a bug for this implementation.

**Pull request closed without merging**
